--local config = {
--    cmd = {'/home/xd/.local/share/nvim/mason/bin/jdtls'},
--    root_dir = vim.fs.dirname(vim.fs.find({'gradlew', '.git', 'mvnw'}, { upward = true })[1]),
--}
--
--require('java').setup()
--require('jdtls').start_or_attach(config)
